version: '3.12'
services:
  web:
    build: .
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
    volumes:
      - .:/app
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - "27017:27017"
  streamlit:
    build: .
    command: streamlit run app.py
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    depends_on:
      - db